CREATE DATABASE AUTO_SCHOOL;

USE AUTO_SCHOOL;

-- Table for learners
CREATE TABLE LEARNER (
    LEARNER_ID INT PRIMARY KEY AUTO_INCREMENT,
    LEARNER_CIN INT NOT NULL,
    LEARNER_FIRST_NAME VARCHAR(50) NOT NULL,
    LEARNER_LAST_NAME VARCHAR(50) NOT NULL,
    LEARNER_PHONE INT(10),
    LEARNER_CITY VARCHAR(50)
);

-- Table for CDs
CREATE TABLE CD (
    CD_ID INT PRIMARY KEY AUTO_INCREMENT,
    CD_EDITEUR_NAME VARCHAR(50) NOT NULL
);

-- Table for series
CREATE TABLE SERIE (
    SERIE_ID INT PRIMARY KEY AUTO_INCREMENT
);

-- Table for sessions
CREATE TABLE SESSION_ (
    SESSION_ID INT PRIMARY KEY AUTO_INCREMENT,
    SESSION_DATE DATE NOT NULL,
    SESSION_TIME TIME NOT NULL,
    SERIE_ID INT,
    CD_ID INT,
    FOREIGN KEY (SERIE_ID) REFERENCES SERIE(SERIE_ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (CD_ID) REFERENCES CD(CD_ID) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- Table for assistance
CREATE TABLE ASSIST (
    LEARNER_ID INT,
    SESSION_ID INT,
    SESSION_NOTE INT(2)
);

-- Table for questions
CREATE TABLE QUESTION (
    QUESTION_ID INT PRIMARY KEY AUTO_INCREMENT,
    INTITULE TEXT,
    ANSWER TEXT,
    DIFFICULTY_LEVEL INT(1),
    THEME TEXT
);

-- Table for question order
CREATE TABLE QUESTION_ORDER (
    QUESTION_ID INT,
    SERIE_ID INT,
    CD_ID INT,
    NUMBER_ORDER INT
);

-- Adding primary keys to ASSIST and QUESTION tables
ALTER TABLE ASSIST ADD PRIMARY KEY (LEARNER_ID, SESSION_ID);
ALTER TABLE QUESTION ADD PRIMARY KEY (QUESTION_ID);

-- Adding foreign key constraints with CASCADE options
ALTER TABLE ASSIST ADD CONSTRAINT fk_LEARNER_ID FOREIGN KEY (LEARNER_ID) REFERENCES LEARNER(LEARNER_ID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE QUESTION_ORDER ADD CONSTRAINT fk_SERIE_ID FOREIGN KEY (SERIE_ID) REFERENCES SERIE(SERIE_ID) ON UPDATE CASCADE ON DELETE CASCADE;

-- Adding a new column to SERIE table
ALTER TABLE SERIE ADD COLUMN NOM_SERIE VARCHAR(50);

-- Modifying the INTITULE column in QUESTION table to TEXT
ALTER TABLE QUESTION MODIFY COLUMN INTITULE TEXT;

-- Adding default value and changing column name in LEARNER table
ALTER TABLE LEARNER ALTER COLUMN LEARNER_CITY SET DEFAULT 'Safi';
ALTER TABLE LEARNER CHANGE COLUMN LEARNER_PHONE GSM_LEARNER VARCHAR(20);

-- Inserting data into LEARNER table
INSERT INTO LEARNER (LEARNER_CIN, LEARNER_FIRST_NAME, LEARNER_LAST_NAME, GSM_LEARNER, LEARNER_CITY) VALUES
(1, 'Allal', 'Alae', '066676676', 'Safi'),
(2, 'Nafisi', 'Najib', '07266262', 'Safi'),
(3, 'Nadir', 'Najat', '09877888', 'Souira');

-- Inserting data into ASSIST table
INSERT INTO ASSIST (LEARNER_ID, SESSION_ID, SESSION_NOTE) VALUES
(1, 1, 'Bien'),
(2, 2, 'Moyen'),
(3, 3, 'Très bien');

-- Inserting data into QUESTION table
INSERT INTO QUESTION (QUESTION_ID, INTITULE, ANSWER, DIFFICULTY_LEVEL, THEME) VALUES
(1, 'Quelle est la capitale du Maroc?', 'Rabat', 1, 'Géographie'),
(2, 'Quel est le plus grand océan?', 'Océan Pacifique', 2, 'Géographie'),
(3, 'Qui a écrit "Les Misérables"?', 'Victor Hugo', 1, 'Littérature');

-- Inserting data into QUESTION_ORDER table
INSERT INTO QUESTION_ORDER (QUESTION_ID, SERIE_ID, CD_ID, NUMBER_ORDER) VALUES
(1, 1, 1, 1),
(2, 1, 1, 2),
(3, 2, 2, 1);

-- Deleting a record from ASSIST table
DELETE FROM ASSIST WHERE LEARNER_ID = 1 AND SESSION_ID = 1;

-- Updating data in LEARNER table
UPDATE LEARNER SET LEARNER_CITY = 'El Jadida' WHERE LEARNER_FIRST_NAME = 'Nafisi' AND LEARNER_LAST_NAME = 'Najib';

-- Truncating QUESTION_ORDER table
TRUNCATE TABLE QUESTION_ORDER;

-- Dropping QUESTION_ORDER table
DROP TABLE QUESTION_ORDER;
